sudo: false
cache:
  directories:
  - node_modules
language: node_js
node_js:
- '0.10'
before_install: npm install -g grunt-cli
after_success: grunt travis
deploy:
  provider: npm
  email: eevert.saukkokoski@appgyver.com
  on:
    tags: true
    all_branches: true
    repo: AppGyver/ag-module-router
  api_key:
    secure: RcYiLvWSmCF+kZ4BVLRLaZ172k9Kj3Dq6TsdoUuKqpTVl0L86vZ6L/PdOE7AlBoNFyEX4PxV93j7gTB5GBV2+y1j+33W1ysaHvc9RX7BB08EGxMPj9oGk7LPaYCq/EUKfHchd9/l1DAgt3rlBddN9PZt4MsxY+prnrfk9X5YE83DJuFmsx/IrbYkxKgjkjf2V3lM38OABBY0Kijbqx4Wc7gEsEXvzY9iwYtM70leLkEqVC/N8GGN/IH7lwiLSjxZAHBHuHmpqht/KP2+0DW353wDst+deXwNMDcXurD9mQcfsOYH3xxCQdbGiAtR+DD1MLMGsS5eWfD4EFPL5LtLcsGqW2LE8C5p4B4+9eV1dB/qFJ8gJI6gIKqCvG3fIwz9p7UOEBQA5eg/9nUG4QO+6L+7EMuvERvOAFy31ksPZ/9ytoOxV+p8oTWFZuMyaSxNjNcZ3y6bOk3l7YzA6uBCG+0y+e1dnvQQs3WrW78eYZaWFPj0MGuNCGHx/IKAmrKOj35kMM16k9Xsh0GTEUOsu/JgPVTrul9hdyn5Weo4xMAfqhcdxNbJcaKvbiQz6wLnhN4et0ahV+KuRH1txlJ2HfF68eDu40ZddJ48qFI/vyhjio042Iu7P/VwQ+40V4gS3k/AipcU9hEZUjLDK5wEDxtKv+FiHvj70Sf0us2PLD4=
env:
  global:
    secure: nqr9ErOkbk1Ym3erbvdqyF5kaWuhNXIsVcbrZmgUXPPhAZMMIHWS5vi9SrmNOQwKy1j66uPMCX41w6jJHW8oNdZ4d6YY+k3kylaxjfGONFVjTb1qSyP09qrCR0pI67MW/tccuL0K2KhG9um+9v+iC/1VvmJxtnsa7trF+zXQljXpvcEJ2WBb5aowXUc+ow/PtFcXcVrN5RVPfh1haHR7YVhyywKh/OCSX/TsBM8+H/YyS9S4Z5+MNF8am14AA+2bDX7sWhECv3+gqQNiGEV/F0eWLlKksdoN2K4iA7ZZiDmlcFRFrw6R28KgBcHNADTDMFEoSSynz3gWT4IaTFNZfCtO4zm2tj79uawnIwVr7GtxLs/uDxinx6bDByQ8oN5BF8Y+xtBUDbsGC4htgWaUTxOCeY8CjqseqhQUsbrjip7cdAsr+o598QFwOOnyhK08nftpePELe/BalMrn57gLMhtvfpY5ilASdKby4mOUFEXGnTxaE3GmBz58OB3J7e3VUDloAUBTbmlOU2JD7hOJef2JR5vs89v6h7pKAHF3CgkoiRiATV3aCDkNkzvN3OS/obuv/XEuZ6dcvOoGJR9uRWweCFDIUewq0A7GRot44/b4/O/FWiDcjJLbMJLWPVG4db9m/C9OzwwmgC+ZcI4DxvvrVhV0PKmc0FW/FXnlrkE=
